name: Run Tests

on:
  push:
    branches:
      - "main"

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Test module
        run: npm i && npm test